QASTUDIODEV/WEB_QASTUDIO

package.json, pnpm-lock.yaml, src/hooks/common/useCustomRedux.ts, src/main.tsx, src/slices/modalSlice.ts, src/store/store.ts
#4 
- @reduxjs/toolkit react-redux redux install
- modal을 예시로 타입 세팅 
N/A
=> [Feature/#4] Redux 설치 및 세팅

src/components/common/sidebar/sidebar.style.ts, src/components/common/sidebar/sidebar.tsx, src/layouts/main/mainLayout.style.ts, src/layouts/main/mainLayout.tsx, src/pages/auth/basicOAuth.tsx, src/pages/auth/githubOAuth.tsx, src/pages/auth/googleOAuth.tsx, src/pages/auth/kakaoOAuth.tsx, src/pages/dashboard/dashboard.style.ts, src/pages/dashboard/dashboard.tsx, src/pages/mypage/mypage.style.ts, src/pages/mypage/mypage.tsx, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx, src/pages/scenario/scenario.style.ts, src/pages/scenario/scenario.tsx, src/pages/scenarioAct/scenarioAct.style.ts, src/pages/scenarioAct/scenarioAct.tsx, src/pages/signup/signup.style.ts, src/pages/signup/signup.tsx, src/routes/index.tsx
#3 
- 라우팅 설정
- 라우팅 설정에 필요한 폴더, 파일 생성
N/A
- 로그인 후 바로 sidebar 최상단 프로젝트의 dashboard가 보여야한다고 합니다! 로그인 후 리다이렉트 시킬 때 `/project/dashboard`로 시킬 테니 `/project/dashboard`로 접근 시 사이드 바의 최상단 프로젝트의 dashboard로 리다이렉트(`/dashboard/:projectId`) 되는 식으로 구현하거나 더 좋은 방법을 떠올려야할 것 같습니다
- 기본적으로 시나리오 실행, 로그인, 회원가입 등을 제외한 부분에서는 사이드바가 항상 존재하기에 mainLayout으로 설정해뒀습니다. 파일 생성만 해둔거라 수정 해주세요!
- 제가 최대한 피그마 보고 라우팅을 설정해두었으나 빠진 부분이나 수정이 필요한 부분이 있을 수 있습니다! 이 부분 유념하시어 개발 부탁드립니다...
- 랜딩 페이지는 프론트 측에서 신경 쓰지 않아도 된다고만 하셔서 랜딩 페이지에 우선 로그인 페이지가 보여지도록 해두었습니다 (사실 이 부분은 잘 모르겠습니다 ㅠㅠ)
=> [Feature/#3] route 설정, 기본적인 폴더 및 파일 세팅

src/components/common/profile/profile.tsx
#15 
- [x ] ✨ Feature Feature
- 기존 '반드시' 프로필 링크를 전달해야했는데 수정을 통해 프로필 링크를 전달하지 않으면, 자동으로 Default 이미지가 보여지도록 수정
N/A
=> [Feature/#15] profile 컴포넌트 props 변경

src/components/common/input/input.style.ts, src/components/common/input/input.tsx
#18 
- 인풋 공용 컴포넌트 제작
N/A
- width는 기본 820px로 되어있습니다.
- onChange에 함수 props를 넘겨서 사용하시면 됩니다
=> feat: 인풋 공용 컴포넌트 제작

src/components/common/button/button.style.ts, src/components/common/button/button.tsx
#22 
- 버튼 컴포넌트 제작
예시)
<Button type="normal" color="default" disabled={true} icon={<Play />} iconPosition="right">
Play
</Button>
=> [Feature/#22] 버튼 공용 컴포넌트 제작

src/pages/addProject/addProject.style.ts, src/pages/addProject/addProject.tsx, src/routes/index.tsx
=> [Feature/#24] 프로젝트 첫 페이지 UI 구현

src/routes/index.tsx
=> [Feature/#26] 마이페이지 라우트 수정

index.html, package.json, pnpm-lock.yaml, src/components/common/modal/modal.style.ts, src/components/common/modal/modal.tsx, src/hooks/common/usePortal.ts, src/pages/dashboard/dashboard.style.ts, src/pages/dashboard/dashboard.tsx, src/slices/modalSlice.ts, src/styles/media.ts, src/styles/theme.ts
#10 
- 모달 컴포넌트 구현 (creatModal 설정)
- 모달 안의 내용이 다양하여 children으로 props 받았습니다
- 스크린샷은 모달 예시입니다
N/A
=> [Feature/#10] modal 컴포넌트 구현

src/components/common/button/button.style.ts, src/components/common/button/button.tsx
=> [Feature/#22] 버튼 공용컴포넌트 색상 옵션 추가

src/components/auth/module/module.style.ts, src/components/auth/socialLogo/socialLogo.style.ts, src/components/auth/socialLogo/socialLogo.tsx, src/pages/login/login.tsx, src/pages/signup/signup.style.ts, src/pages/signup/signup.tsx
#37 
소셜 로그인 컴포넌트 수정
컴포넌트 수정에 따른 사용법 반영
- N/A
=> [Feature/#37] 소셜로고 컴포넌트 수정, 컴포넌트 수정에 따른 사용법 반영

src/components/auth/socialLogo/socialLogo.style.ts, src/components/auth/socialLogo/socialLogo.tsx
#40 
isGithub?; boolean => $isgithub?: string으로 변경
gap: number => $gap: number으로 변경
N/A
=> [Feature/#40] 브라우저 warning 제거를 위한 props 타입 및 용어 변경

src/layouts/main/mainLayout.style.ts, src/layouts/main/mainLayout.tsx
=> [Feature/#43] OutletWrapper 생성

src/layouts/main/mainLayout.style.ts
- 깨지는 레이아웃 방지를 위해 max width와 overflow-x hidden 설정
N/A
=> [Feature/#45] 레이아웃이 깨지는 현상 수정

src/components/common/modal/modal.style.ts, src/components/common/modal/modal.tsx
- 로그아웃 모달에 X 버튼이 없어 이부분도 props로 받는걸로 설정
- 스크롤 추가해달라고 하셔서 overflow 추가했습니다아 
N/A
=> ✨ [Feature] modal 컴포넌트 수정

.github/workflows/ci.yaml, .github/workflows/main.yaml
#36 
- ci/cd setting
잘 된건지 테스트좀 해보겠습니다앗...
=> ⚙️ [Setting] ci/cd setting

src/components/common/profile/profile.style.ts
=> [Feature/#69] 프로필 공용 컴포넌트 css 추가

src/assets/icons/arrow_left.svg, src/assets/icons/arrow_right.svg, src/components/dashboard/progressBar/progressBar.style.ts, src/components/dashboard/progressBar/progressBar.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/hooks/common/useDebounce.ts, src/pages/dashboard/dashboard.style.ts, src/pages/dashboard/dashboard.tsx
#68 
- 대시보드 레이아웃 수정
- 검색창 디바운스 hook 추가 
- 콘솔 warning 제거 (스타일 컴포넌트 props 명칭 관련 $ 추가)
=> ✨ [Feature] 대시보드 레이아웃 수정

src/components/common/sidebar/sidebar.style.ts, src/components/common/sidebar/sidebar.tsx
=> [Feature/#75] 반응형 sidebar UI 구현

src/apis/auth/auth.ts, src/apis/axiosInstance.ts, src/main.tsx, src/pages/auth/authHandler.tsx, src/pages/login/login.tsx, src/pages/signup/signup.tsx, src/routes/index.tsx, src/slices/authSlice.ts, src/store/store.ts
#52
- ProtectedRoute 생성
- axiosInterceptor를 이용한 리프레시 준비 (아직 api가 없어 만들어만 뒀습니다)
추후 어느정도 윤곽이 잡히면 ProtectedRoute 설정을 하겠습니다
빌드 오류때문에 mypage에만 설정해뒀습니다
=> [Feature/#52] 로그인 상태 전역관리

src/pages/findingPassword/findingPassword.tsx
=> [Feature/#80] 코드 구조 변경, API 임시 연결

src/components/common/sidebar/sidebar.style.ts, src/layouts/main/mainLayout.style.ts
#82 
N/A
- 개선이 필요하시면 언제든 연락주세용
=> [Feature/#82] 사이드바 개선

src/components/mypage/myProfile/MyProfile.style.ts, src/components/mypage/myProfile/myProfile.tsx, src/components/mypage/projectList/projectList.style.ts, src/components/mypage/projectList/projectList.tsx, src/components/mypage/projectNum/projectNum.style.ts, src/pages/mypage/mypage.style.ts
=> [Feature/#79] mypage 반응형 추가

src/apis/auth/auth.ts, src/apis/images/images.ts, src/apis/mypage/mypage.ts, src/apis/userController/userController.ts, src/components/mypage/myProfile/myProfile.tsx, src/hooks/images/useGetPresignedURL.ts, src/hooks/images/useUploadPresignedURL.ts, src/pages/userSetting/userSetting.tsx, src/types/auth/auth.ts
#73 
- api 연결
- 사진 Put하는 api 비동기 방식으로 변경 (변경에 따른 사용법 수정)
N/A
=> [Feature/#73] usersetting api 연결

src/components/common/input/validationMessage.style.ts, src/components/common/input/validationMessage.tsx, src/components/projectInfo/pageModal/pageModal.tsx, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx
=> [Feature/#85] information 페이지 반응형 구현

src/apis/error/error.ts, src/apis/test/test.ts, src/constants/querykeys/queryKeys.ts, src/enums/enums.ts, src/hooks/error/useGetError.ts, src/hooks/test/useGetStatistics.ts, src/hooks/test/usePaginateSearchTestList.ts, src/hooks/test/usePaginateTestList.ts, src/types/error/error.ts, src/types/test/test.ts
#98 
- error, test api, hook 정리 
N/A
api는 백엔드에서 완료되지 않아 연결은 하지 않고 
나중에 편의를 위해 api hook만 정리해두었습니다
=> [Feature/#98] 대시보드 api 정리 

src/components/dashboard/selectBox/selectBox.style.ts, src/components/dashboard/selectBox/selectBox.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/constants/state/state.ts, src/mocks/tableData.ts, src/styles/global.ts
=> [Feature/#60] select 컴포넌트 생성

src/components/scenario/buttonGroup/buttonGroup.tsx, src/components/scenario/characterHeader/characterHeader.style.ts, src/components/scenario/characterHeader/characterHeader.tsx, src/components/scenario/characterList/characterList.tsx, src/components/scenario/dropDown/dropDown.tsx, src/components/scenario/scenarioItem/scenarioItem.style.ts, src/components/scenario/scenarioItem/scenarioItem.tsx, src/routes/index.tsx, src/slices/scenarioSlice.ts
#100 
- 아이콘 수정
- 선택 기능 추가(선택되면 백그라운드 색 바뀜)
- 리덕스 수정
- index 수정
N/A
=> [Feature/#100] 시나리오 조회 아이콘 수정, 선택 기능 추가

src/pages/signup/signup.tsx
#113 
회원가입 후 프로필 수정시 401에러 수정 
회원가입 후 로그인 mutation이 실행되었으나 전역상태로 토큰을 저장하지 않아 문제가 생긴 것 같았습니다.
따라서 성공시에 데이터를 저장할 수 있도록 로그인 로직과 같이 dispatch를 추가하였습니다. 
N/A
=> 🐞 [BugFix] 회원가입 후 프로필 세팅 오류 수정

src/components/common/input/input.style.ts, src/components/common/input/input.tsx
#115 
- thin 타입 추가(시나리오 실행, 시나리오 추가에서 쓰겠습니다)
- N/A
=> [Feature/#115] 인풋 thin 타입 추가

src/apis/sidebar/sidebar.ts, src/components/common/sidebar/projectModal/projectModal.style.ts, src/components/common/sidebar/projectModal/projectModal.tsx, src/components/common/sidebar/sidebar.tsx, src/constants/querykeys/queryKeys.ts, src/hooks/sidebar/sidebar.ts, src/hooks/sidebar/useGetTeamMember.ts, src/types/sidebar/sidebar.ts
#111 
- 프로젝트 조회
- 이미지 업로드
- 프로젝트 추가 + 이메일 조회
임시로 올렸습니당
=> [Feature/#111] 사이드바 api 연결 1차

src/apis/axiosInstance.ts, src/pages/login/login.tsx, src/pages/loginRedirect/loginRedirect.tsx, src/pages/signup/signup.tsx, src/slices/authSlice.ts
#125 
- 쿠키 방식으로 로그인/회원가입 방식 변경
N/A
=> [Feature/#125] 소셜로그인, 일반 로그인 쿠키 방식으로 변경

src/components/common/sidebar/sidebar.tsx, src/hooks/sidebar/sidebar.ts, src/pages/login/login.tsx, src/pages/loginRedirect/loginRedirect.tsx
- 로그인 무한 리렌더링 수정
N/A
임시로 수정한 거라 나중에 수정이 필요합니다
제 생각엔 로그인시 nickname을 그냥받아버려서 처리하는게 요청 수도 줄어들어서 좋을 것 같은 판단이긴한데 
서버를 몰라서..서버분들에게 논의를 해봐야할 것 같습니다.
=> 🐞 [BugFix] 로그인 무한 리렌더링 수정

package.json, pnpm-lock.yaml
=> [Feature/#129] 윈도우 세팅

src/pages/login/login.tsx, src/pages/userSetting/userSetting.tsx, src/types/auth/auth.ts
#133 
- 로그인 response에 따라 /signup/userSetting or /project 으로 navigate 시킴
- response 추가로 api 호출은 삭제
N/A
=> [Feature/#133] 로그인 Response 변경에 따른 수정

src/components/projectInfo/toolTip/toolTip.style.ts, src/components/projectInfo/toolTip/toolTip.tsx, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx
=> [Feature/#136] tooltip 구현

src/pages/userSetting/userSetting.tsx
=> [Feature/#149] 에러 해결

src/components/common/sidebar/projectModal/projectModal.style.ts, src/components/common/sidebar/projectModal/projectModal.tsx, src/components/common/sidebar/sidebar.style.ts
#140 
- width 스크롤 없애기
- 프로젝트 프로필 등록 UI 변경
- isPending 추가
N/A
=> [Feature/#140] 프로젝트 모달 수정

src/components/common/button/button.style.ts
=> [Refactor/#154] 버튼 UI 업데이트

src/apis/projectInfo/projectInfo.ts, src/components/projectInfo/characterModal/characterModal.style.ts, src/components/projectInfo/characterModal/characterModal.tsx, src/components/projectInfo/inviteModal/inviteModal.style.ts, src/components/projectInfo/inviteModal/inviteModal.tsx, src/components/projectInfo/pageModal/pageModal.style.ts, src/components/projectInfo/pageModal/pageModal.tsx, src/hooks/projectInfo/useProjectInfo.ts, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx, src/types/projectInfo/projectInfo.ts
=> [Feature/#153] Introduce 수정 API 연결

src/apis/projectInfo/projectInfo.ts, src/components/common/sidebar/projectModal/projectModal.tsx, src/components/projectInfo/inviteModal/inviteModal.tsx, src/constants/querykeys/queryKeys.ts, src/hooks/projectInfo/useProjectInfo.ts, src/pages/projectInfo/projectInfo.tsx, src/types/projectInfo/projectInfo.ts
#157 
- 프로젝트 팀원을 조회하는 api 연결
- 유효성 검사 추가
=> [Feature/#157] 프로젝트 팀원 조회 API 연결

src/components/common/projectTitle/projectTitle.style.ts, src/components/common/projectTitle/projectTitle.tsx, src/components/scenario/characterHeader/characterHeader.style.ts, src/components/scenario/characterHeader/characterHeader.tsx, src/components/scenario/scenarioItem/scenarioItem.style.ts, src/components/scenario/scenarioItem/scenarioItem.tsx, src/components/scenario/scenarioModal/scenarioModal.style.ts, src/components/scenario/scenarioModal/scenarioModal.tsx, src/pages/scenario/scenario.style.ts, src/slices/scenarioSlice.ts
#161 
- 폰트 수정
- padding 수정
- 화면 크기에 대한 반응형
- 모달
N/A
=> [Feature/#161] 시나리오 조회 UI 수정 

src/apis/error/error.ts, src/components/common/modal/modal.style.ts, src/components/dashboard/errorModal/errorModal.style.ts, src/components/dashboard/errorModal/errorModal.tsx, src/components/dashboard/table/table.tsx, src/components/scenario/scenarioModal/scenarioModal.tsx, src/slices/modalSlice.ts, src/styles/global.ts
#112 
run 시나리오 경로가 어딘지 정확히 모르겠습니다 (수정 가능성 있음)
replay클릭시 뭐가 리플레이 되는건지 모르겠음 (경로 이동일 가능성) 
-> 둘다 시나리오 실행으로 이동
=> ✨ [Feature] 에러보드 api 연결 

src/pages/addProject/addProject.tsx
=> [Fix/#171] navigate 오류 해결

src/apis/projectInfo/projectInfo.ts, src/components/projectInfo/pageModal/pageModal.style.ts, src/components/projectInfo/pageModal/pageModal.tsx, src/components/projectInfo/toolTip/toolTip.tsx, src/constants/querykeys/queryKeys.ts, src/hooks/projectInfo/useAddPage.ts, src/hooks/projectInfo/useGetScenario.ts, src/hooks/projectInfo/useProjectInfo.ts, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx, src/pages/projectInfo/projectStructure.style.ts, src/pages/projectInfo/projectStructure.tsx, src/types/projectInfo/projectInfo.ts
=> [Feature/#170] 페이지 생성 API 연결

src/apis/auth/auth.ts, src/apis/axiosInstance.ts, src/components/common/sidebar/logtoutModal/logoutModal.tsx, src/slices/authSlice.ts
#163 
- 로그아웃 api 연결
- 리프레시 api 연결
N/A
사이드바에도 로그아웃 연결 제가 해뒀습니다! 바로 사용 가능합니다~
=> [Feature/#163] 로그아웃, 리프레시 api 연결

src/components/common/input/input.style.ts, src/components/common/projectTitle/projectTitle.style.ts
#174 
- 공용 인풋 height, width 변경
- 프로젝트타이틀 수정
N/A
=> [Feature/174] 공용 인풋, projectTitle 디자인 수정

src/apis/projectInfo/projectInfo.ts, src/components/projectInfo/characterModal/characterModal.tsx, src/components/projectInfo/toolTip/toolTip.tsx, src/constants/querykeys/queryKeys.ts, src/hooks/projectInfo/useProjectInfo.ts, src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx, src/pages/projectInfo/projectStructure.style.ts, src/pages/projectInfo/projectStructure.tsx, src/types/projectInfo/projectInfo.ts
#170 
- Info UI 수정
- page 조회 API 연결
=> [Feature/#170] UI 수정 및 API 연결

src/components/common/input/input.style.ts, src/components/scenario/buttonGroup/buttonGroup.style.ts, src/components/scenario/buttonGroup/buttonGroup.tsx, src/components/scenario/characterHeader/characterHeader.style.ts, src/components/scenario/characterHeader/characterHeader.tsx, src/components/scenario/dropDown/dropDown.style.ts, src/components/scenario/scenarioItem/scenarioItem.style.ts, src/components/scenario/scenarioItem/scenarioItem.tsx, src/components/scenarioAct/actionItem/actionItem.style.ts, src/components/scenarioAct/actionItem/actionItem.tsx, src/components/scenarioAct/addInputForm/addInputForm.style.ts, src/components/scenarioAct/controller/controller.style.ts, src/components/scenarioAct/controller/controller.tsx, src/components/scenarioAct/header/header.style.ts, src/components/scenarioAct/recordItem/recordItem.style.ts, src/components/scenarioAct/recordItem/recordItem.tsx, src/components/scenarioAct/scenarioItem/scenarioItem.style.ts, src/components/scenarioAct/scenarioItem/scenarioItem.tsx, src/components/scenarioAct/selectDropdown/selectDropdown.style.ts, src/components/scenarioAct/selectDropdown/selectDropdown.tsx, src/components/scenarioAct/thinDropdown/thinDropdown.style.ts, src/components/scenarioAct/thinDropdown/thinDropdown.tsx, src/pages/scenario/scenario.style.ts, src/pages/scenario/scenario.tsx, src/pages/scenarioAct/scenarioAct.style.ts
- 폰트 및 컴포넌트 스타일 변경
N/A
인풋도 살짝..
=> ✨ [Feature/175] 시나리오 조회, 실행 UI 수정

src/components/dashboard/calendar/calendar.tsx, src/components/dashboard/table/pageNameHeader.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/pages/dashboard/dashboard.style.ts, src/pages/dashboard/dashboard.tsx, src/slices/calendarSlice.ts, src/types/test/test.ts
#176 
- 달력/검색창 연결
N/A
추후에 useState 삭제하고 path params로 변경해서 하려고합니다..
=> ✨ [Feature] 표 api 검색/달력 연결

src/apis/axiosInstance.ts, src/components/auth/authModal/authModal.style.ts, src/components/auth/authModal/authModal.tsx, src/components/common/modalProvider/modalProvider.tsx, src/hooks/auth/useAuthModal.ts, src/pages/login/login.style.ts
#184 
- 로그인 화면 글자색상 변경
- 미로그인 상태로 다른 url 접속시(로그인이 필요한 url) 모달 띄우기
N/A
=> [Feature/#184] 1차 통합 테스트 피드백 수정

src/components/common/loading/loading.style.ts
#186 
-  로딩 컴포넌트 투명도 조절 50%
N/A
=> ✨ [Feature] 로딩 컴포넌트 투명도 조절

src/components/scenario/dropDown/dropDown.style.ts, src/components/scenario/scenarioModal/scenarioModal.style.ts
#188 
- 역할 생성 모달 UI 수정
- access Page 드롭다운 수정
- N/A
=> ✨ [Feature/#188] 1차 통합 테스트 피드백 UI 수정

src/apis/axiosInstance.ts
#190 
- refresh 성공 후 logout시키는 에러 해결
N/A
=> [bug] fix: 에러 해결

src/apis/axiosInstance.ts
#194 
- 비밀번호나 이메일을 틀려 로그인에 실패했을 때 로그인하라는 모달이 뜨는 에러를 해결
N/A
=> [Bug] 로그인 실패시 모달이 뜨는 에러

.github/workflows/ci.yaml
=> ⚙️ [Setting] pnpm 관련 빌드 오류 수정

src/components/dashboard/table/pageNameHeader.tsx, src/components/dashboard/table/table.tsx, src/types/test/test.ts
- 표 Header page api 연결 
- page 수정 
N/A
=> ✨ [Feature] 표 Header page api 연결 

src/components/auth/module/module.style.ts, src/components/auth/module/module.tsx, src/components/findingPassword/findingPasswordStep1.tsx, src/components/findingPassword/findingPasswordStep2.tsx, src/components/mypage/myProfile/myProfile.tsx, src/pages/findingPassword/findingPassword.tsx, src/pages/login/login.tsx, src/pages/signup/signup.tsx, src/pages/userSetting/userSetting.tsx
#203 
- 실시간 검사 수정
- 에러 반환 문구 수정
N/A
PM분이 원하시는 기능은 touchedFields를 사용하면 안되어서 전부 useWatch로 검사합니다.
=> [Bug/#203] input박스 밖을 클릭 하지 않아도 검사 되도록 수정

src/components/auth/module/module.tsx, src/components/findingPassword/findingPasswordStep1.tsx, src/pages/findingPassword/findingPassword.tsx, src/pages/signup/signup.tsx
=> fix: disable 처리

src/pages/scenario/scenario.style.ts
=> [bug] height 수정

src/pages/addProject/addProject.tsx
=> [Bug/#213] route 오류 수정

src/pages/projectInfo/projectInfo.style.ts, src/pages/projectInfo/projectInfo.tsx, src/pages/projectInfo/projectStructure.style.ts, src/pages/projectInfo/projectStructure.tsx
#215 
- 팀원 마이페이지 연결
- 스타일 수정
N/A
=> [Feature/#215] 팀원 마이페이지 연결 및 스타일 수정

src/pages/error/error.style.ts, src/pages/error/error.tsx, src/routes/index.tsx, src/styles/theme.ts
=> ✨ [Feature] 공용 not-found

src/components/common/modal/modal.tsx, src/components/scenario/scenarioModal/scenarioModal.tsx
#221 
- clickOutside 삭제 
- 모달 밖 onClick 삭제 
N/A
=> ♻️ [Refactor] modal 수정

src/apis/images/images.ts, src/components/mypage/myProfile/MyProfile.style.ts, src/components/mypage/myProfile/myProfile.tsx, src/components/mypage/projectList/projectList.tsx, src/components/mypage/projectNum/projectNum.tsx, src/pages/mypage/mypage.style.ts, src/pages/mypage/mypage.tsx, src/utils/santizeFilename.ts
#210 
- 마이페이지 접속 시 로딩 추가
- edit 상태가 아니면 hover해도 pointer가 되지 않도록 수정
N/A
=> [Refactor/#210] 마이페이지 리팩토링

src/components/mypage/myProfile/MyProfile.style.ts, src/components/mypage/myProfile/myProfile.tsx
#227 
- userInfo를 감싸고 있던 div 삭제
N/A
=> [Bugfix] 배너 이미지 클릭 시 input이 잘 열리도록 수정

src/components/auth/inviteModal/inviteErrorModal.tsx, src/components/auth/inviteModal/inviteModal.style.ts, src/components/auth/inviteModal/inviteSuccessModal.tsx, src/components/auth/inviteModal/inviteTokenExpiredModal.tsx
=> [Feature] 모달 안내 문구 및 디자인 변경

src/components/dashboard/selectBox/selectBox.style.ts
#241 
- 표 selectbox에서 max-height 설정 (page 데이터가 많은 경우, 표 아래로 넘치는 것 방지)
- 표 리팩토링 진행 및 페이지 처리 
- 표 시나리오 실행  관련 > 레코드 실행 
BugFix라벨이 아니라 Feature인 것 같기도한데 일단 다음부턴 Feature로 진행하겠습니다
=> 🐞 [BugFix] pageName이 많아졌을 때 표 스크롤 수정

src/components/scenarioAct/actSection/actSection.tsx, src/components/scenarioAct/controller/controller.tsx, src/pages/scenarioAct/scenarioAct.style.ts, src/pages/scenarioAct/scenarioAct.tsx
=> 🐞 [BugFix/#246] 시나리오 실행 역할 선택 오류 해결

src/components/scenario/characterHeader/characterHeader.tsx, src/components/scenario/characterList/characterList.tsx, src/components/scenario/scenarioItem/scenarioItem.style.ts, src/components/scenario/scenarioItem/scenarioItem.tsx, src/pages/scenario/scenario.tsx
=> [Refactor] 시나리오 클릭시 활성화 되게 수정

src/components/dashboard/projectStatistics/projectStatistics.tsx, src/components/dashboard/table/pageNameHeader.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/hooks/common/customQuery.ts, src/hooks/common/useProjectId.ts, src/hooks/test/usePaginateTestList.ts, src/pages/dashboard/dashboard.tsx
#245 
- 표 리랜더링시 통게부분이 같이 리랜더링 되는 것 방지 
- 표 부분 스캘레톤 추가 
- 쿼리 staleTime을 전역적으로 지정하여 5분 캐시 -> 5분이내 동일한 요청은 안가도록 설정 
- 표 헤더 리팩토링 
- 표 > 레코드 실행 연결 
=> ♻️ [Refactor] 표 select로 변경시 통계 리렌더링 이슈 해결

src/utils/getPageNumbers.ts
=> [Bug] 페이지 버튼 반환 함수 수정

src/components/dashboard/calendar/calendar.tsx, src/components/dashboard/selectBox/selectBox.style.ts, src/components/dashboard/table/dateHeader.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/slices/calendarSlice.ts, src/utils/formatDate.ts, src/utils/getPageNumbers.ts
#260 
- 버튼 1-10으로 수정 
- 표 Padding 변경
- 캘린더 날짜 버튼을 눌렀을때만 닫히게 수정(월별 이동시에는 닫히지 않도록)
N/A
=> 🐞 [BugFix] 표 페이지네이션 버튼 오류 수정 및 표 캘린더 오류 수정

src/components/dashboard/calendar/calendar.tsx, src/components/dashboard/selectBox/selectBox.style.ts, src/components/dashboard/table/dateHeader.tsx, src/components/dashboard/table/table.style.ts, src/components/dashboard/table/table.tsx, src/slices/calendarSlice.ts, src/utils/formatDate.ts, src/utils/getPageNumbers.ts
=> 🌏 [Deploy] 표 관련 오류사항 수정 배포 

src/apis/scenarioAct/scenarioAct.ts, src/components/common/input/input.tsx, src/components/scenarioAct/actSection/InnerComponent.tsx, src/components/scenarioAct/actionItem/actionItem.tsx, src/components/scenarioAct/addInputForm/addInputForm.tsx, src/components/scenarioAct/input/input.style.ts, src/components/scenarioAct/input/input.tsx, src/components/scenarioAct/scenarioItem/scenarioItem.tsx, src/hooks/scenarioAct/useWebsocket.ts, src/pages/scenarioAct/scenarioAct.tsx, src/slices/scenarioActSlice.ts
#247 
- write directly
- 시나리오 실행 시 플레이 아이콘 변경
- 프로젝트url 하드코딩 제거
=>  [Feature/#247] 시나리오 실행 남은 기능들

src/apis/projectInfo/projectInfo.ts, src/components/common/modal/modal.style.ts, src/components/common/modalProvider/modalProvider.tsx, src/components/common/projectHeader/projectHeader.style.ts, src/components/common/projectHeader/projectHeader.tsx, src/components/common/projectTitle/projectTitle.style.ts, src/components/common/projectTitle/projectTitle.tsx, src/components/common/sidebar/projectProfile/projectProfile.tsx, src/components/dashboard/projectStatistics/projectStatistics.style.ts, src/components/dashboard/projectStatistics/projectStatistics.tsx, src/components/projectInfo/deleteProjectModal/deleteProjectModal.style.ts, src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx, src/components/projectInfo/editProjectModal/editProjectModal.style.ts, src/components/projectInfo/editProjectModal/editProjectModal.tsx, src/enums/enums.ts, src/hooks/projectInfo/useProjectInfo.ts, src/layouts/main/mainLayout.style.ts, src/layouts/main/mainLayout.tsx, src/pages/dashboard/dashboard.style.ts, src/pages/scenario/scenario.style.ts, src/pages/scenario/scenario.tsx, src/types/projectInfo/projectInfo.ts
#263 
- 위치를 맞춰달라는 PM분의 요청이 있어서 따로 맞추기엔 어려움이 있어보여 헤더를 컴포넌트로 분리하고 레이아웃에 추가하였습니다.
- result type 변경
- N/A
- 기존 본인이 담당하신 부분에서 작성하신 코드는 제가 삭제했다가 충돌이 날까봐... 우선 제 담당 (시나리오 조회) 부분은 수정을 해뒀는데 기존 본인 코드에서 프로젝트 헤더부분은 삭제해주세요!! (아마 지금 두개가 보일겁니다..)
=> [Bugfix/#263] 프로젝트 헤더 (프로젝트 네임, 프로젝트 스택) 공용컴포넌트 분리, 레이아웃에 추가

src/components/projectInfo/deleteProjectModal/deleteProjectModal.tsx
=> [Feature] 프로젝트 삭제 모달에 취소 버튼 추가

src/components/common/loading/modalLoading.style.ts, src/components/common/loading/modalLoading.tsx, src/components/common/projectTitle/projectTitle.tsx, src/components/common/sidebar/projectModal/projectModal.tsx, src/components/projectInfo/editProjectModal/editProjectModal.tsx, src/components/projectInfo/inviteModal/inviteModal.tsx, src/components/scenario/scenarioModal/scenarioModal.tsx, src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx
#275 
- 모달로딩을 따로 컴포넌트를 만들고 적용했습니다
- 제가 아는 선에서는 다 적용 시켜놨는데 혹시 빠진 부분 있으면... 추가해주세용...
=> [Refactor/#275] 모달 로딩 디자인 변경 및 반영

src/components/common/profile/profile.tsx
#280 
- 이미지 url이 올바르지 않은 경우 프로젝트면 프로젝트 기본 이미지, 유저프로필이면 유저 프로필 기본 이미지로 설정
N/A
=> [Bugfix] 이미지 url이 올바르지 않을 때 깨져보이는 현상 예외처리

src/components/common/projectHeader/projectHeader.tsx, src/types/projectInfo/projectInfo.ts
#277
- api response type 추가
- 예외처리
N/A
=> [Refactor] 프로젝트 리더만 edit, delete 버튼이 보이도록 수정

src/components/mypage/myProfile/MyProfile.style.ts, src/components/mypage/projectList/projectList.style.ts, src/components/mypage/projectList/projectList.tsx, src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx, src/components/userInfo/userProfile/userProfile.style.ts, src/components/userInfo/userProfile/userProfile.tsx, src/hooks/userInfo/useOtherUserInfo.ts, src/pages/mypage/mypage.tsx, src/pages/userInfo/userInfo.style.ts, src/pages/userInfo/userInfo.tsx
#253
- 마이페이지 불필요한 리랜더링 제거, userInfo 불필요한 리랜더링 제거
- 미디어 쿼리 수정
- 누락된 스타일 추가
- 마이페이지에서 프로필을 수정하면 사이드바에 있는 프로젝트도 리랜더링 되는데 이유를 모르겠습니다....
=> [Refactor/#253] 마이페이지 리팩토링

src/apis/axiosInstance.ts, src/components/common/sidebar/logtoutModal/logoutModal.tsx, src/hooks/auth/useUserAuth.ts, src/pages/login/login.tsx, src/pages/signup/signup.tsx
#259 
- 로그인 된 상태(쿠키가 있고, 만료되지 않은 상태)이면 '/'나 '/signup' 접근 시 자동으로 '/project'로 navigate되도록 설정
N/A
=> [Refactor] auth 리팩토링

src/components/common/modal/modal.style.ts, src/components/dashboard/errorModal/errorModal.style.ts, src/components/dashboard/table/table.style.ts, src/components/scenarioAct/scenarioActModal/scenarioActModal.style.ts
=> ✨ [Feature] 에러 모달 수정

src/components/common/modal/modal.style.ts, src/components/dashboard/errorModal/errorModal.style.ts, src/components/dashboard/table/table.style.ts, src/components/scenarioAct/scenarioActModal/scenarioActModal.style.ts
- 에러 모달관련 스타일 수정 배포브랜치에 반영
N/A
=> 🌏 [Deploy] 에러 모달 수정 배포 브랜치에 반영

src/apis/axiosInstance.ts
=> [Refactor/#300] axiosInterceptor 리팩토링

src/components/dashboard/progressBar/progressBar.style.ts
=> ✨ [Feature] 대시보드 100% 짤리는 이슈 수정 

src/components/dashboard/progressBar/progressBar.style.ts
#305 배포 브랜치에 반영 
#305 에 캡쳐 부분 
N/A
=> 🌏 [Deploy] 대시보드 100% 짤리는 부분 수정 

src/apis/scenario/scenario.ts, src/components/scenario/scenarioModal/scenarioModal.tsx, src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep.style.ts, src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep1.tsx, src/components/scenario/scenarioModal/scenarioModal/scenarioModalStep2.tsx, src/types/scenario/scenario.ts
#307 
- 시나리오 생성
N/A
- 현재 서버측 파싱 에러로 ai로부터 
```
code:  "COMMON500"
isSuccess: false
message: "Server error, please contact the administrator."
result:  "Unexpected character ('{' (code 123)): was expecting double-quote to start field name\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 444]"
```
이런 에러가 오는 경우가 있는데 이는 해결해 보시겠다고 하셨습니다. 이 에러가 발생할 때도 있고 아닐 때도 있어서 우선 무시해주시면 됩니다
=> [Feature/#307] 캐릭터 생성 시 ai 시나리오를 선택해서 만들 수 있도록 수정

src/components/common/sidebar/logtoutModal/logoutModal.tsx, src/pages/mypage/mypage.style.ts
#319 
- 전에 메인 레이아웃을 바꾸면서 마이페이지 스타일에 영향이 간 걸 알았고, 수정하였습니다
N/A
=> [Refactor] 마이페이지 스타일 수정

src/components/userInfo/otherUserProjectList/otherUserProjectList.tsx, src/hooks/userInfo/useOtherUserInfo.ts, src/hooks/userInfo/useOtherUserProjects.ts, src/pages/findingPassword/findingPassword.tsx, src/pages/userInfo/userInfo.tsx
- findingpassword 성공 시 / 로 navigate
- 다른 유저의 마이페이지를 불러올 때 page가 undefined로 요청가는 에러 해결
N/A
=> [Refactor] 맡은 부분 리팩토링

src/components/scenarioAct/addInputForm/addInputForm.tsx, src/components/scenarioAct/continueModal/continueModal.style.ts, src/components/scenarioAct/controller/controller.style.ts, src/components/scenarioAct/modifyInputForm/modifyInputForm.tsx
=> [Refactor/#325] 시나리오 실행 UI 수정

src/pages/addProject/addProject.tsx
=> [Refactor/#330] invalidate 쿼리 추가
